### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by jasc22** [JamesCooteUK/SharpSphere#5]
Hey James,
I was testing your tool and an into the following error in the screenshot below. I enabled all versions of SSL/TLS within ESXi 6.5 and on the Windows 10 host within the .NET framework to get it to work and kept getting a 400 error code. I'm able to access ESXi via the browser without any issues.

![image](https://user-images.githubusercontent.com/29802479/110867370-762a3d00-827b-11eb-91c9-7dd5b149b213.png)

Appreciate your help with this.

Thanks!

**Comment by JamesCooteUK** [comment]
Hi, you need to supply the full url to the Api, so in this case it'll be https://10.22.1.44/sdk

There's been limited testing against ESXi hosts directly, it's been mainly through vCenter, so let me know if you run into any other issues.

**Comment by jasc22** [comment]
Thanks for your response, James.

I was able to successfully authenticate but get the following error below.

"Error: Object reference not set to an instance of an object."

**Comment by JamesCooteUK** [comment]
Can you provide the full output? Including which module you ran? Should imagine this is due to differences between ESXi/vCenter but will take a look for you if you can provide some more details.

**Comment by RicterZ** [comment]
I had same issue while testing on vCenter Server 7.0U2b
```
C:\Users\RicterZ\Downloads>SharpSphere.exe list --url https://192.168.100.49:443/sdk/ --username administrator@vsphere.local --password xxx
[x] Disabling SSL checks in case vCenter is using untrusted/self-signed certificates
[x] Creating vSphere API interface, takes a few minutes...
Error: An error occurred while making the HTTP request to https://192.168.100.49/sdk/. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server.
```

**Comment by JamesCooteUK** [comment]
@jasc22 and @RicterZ I've just pushed a change that should fix those issues, sorry for the delay. With the latest version(s) of vCenter it failed negotiating the version of TLS to use. I'll keep this issue open for a while in case that wasn't the cause.

**Comment by jasc22** [comment]
Thanks, @JamesCooteUK! I tested the latest version and observed the same issue. Appreciate your help with this.

**Comment by JamesCooteUK** [comment]
You recompiled the project from the latest master yeah? Not using the version from Releases?

**Comment by jasc22** [comment]
Looks like I compiled the original one. I can confirm that SharpSphere-Master works. Thanks, James!
